/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eAdBuddiz.h"


// Define S3E_EXT_SKIP_LOADER_CALL_LOCK on the user-side to skip LoaderCallStart/LoaderCallDone()-entry.
// e.g. in s3eNUI this is used for generic user-side IwUI-based implementation.
#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
#if defined I3D_ARCH_MIPS || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP)) || defined I3D_ARCH_NACLX86_64
// For platforms missing stack-switching (MIPS, WP8, NaCl, etc.) make loader-entry via LoaderCallStart/LoaderCallDone() on the user-side.
#define LOADER_CALL_LOCK
#endif
#endif


#include "s3eAdBuddiz_interface.h"

static s3eAdBuddizFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0x1b0b6597, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eAdBuddiz");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0x1b0b6597, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eAdBuddizAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eAdBuddizRegister(s3eAdBuddizCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(ADBUDDIZ_VERBOSE, ("calling s3eAdBuddiz[0] func: s3eAdBuddizRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizRegister);
#endif

    s3eResult ret = g_Ext.m_s3eAdBuddizRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizRegister);
#endif

    return ret;
}

s3eResult s3eAdBuddizUnRegister(s3eAdBuddizCallback cbid, s3eCallback fn)
{
    IwTrace(ADBUDDIZ_VERBOSE, ("calling s3eAdBuddiz[1] func: s3eAdBuddizUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizUnRegister);
#endif

    s3eResult ret = g_Ext.m_s3eAdBuddizUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizUnRegister);
#endif

    return ret;
}

s3eResult s3eAdBuddizInitialize(const char* publisherKey)
{
    IwTrace(ADBUDDIZ_VERBOSE, ("calling s3eAdBuddiz[2] func: s3eAdBuddizInitialize"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizInitialize);
#endif

    s3eResult ret = g_Ext.m_s3eAdBuddizInitialize(publisherKey);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizInitialize);
#endif

    return ret;
}

s3eResult s3eAdBuddizSetTestMode()
{
    IwTrace(ADBUDDIZ_VERBOSE, ("calling s3eAdBuddiz[3] func: s3eAdBuddizSetTestMode"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizSetTestMode);
#endif

    s3eResult ret = g_Ext.m_s3eAdBuddizSetTestMode();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizSetTestMode);
#endif

    return ret;
}

s3eResult s3eAdBuddizShowAd()
{
    IwTrace(ADBUDDIZ_VERBOSE, ("calling s3eAdBuddiz[4] func: s3eAdBuddizShowAd"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizShowAd);
#endif

    s3eResult ret = g_Ext.m_s3eAdBuddizShowAd();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizShowAd);
#endif

    return ret;
}

s3eResult s3eAdBuddizSetLogLevel(s3eAdBuddizLogLevel logLevel)
{
    IwTrace(ADBUDDIZ_VERBOSE, ("calling s3eAdBuddiz[5] func: s3eAdBuddizSetLogLevel"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizSetLogLevel);
#endif

    s3eResult ret = g_Ext.m_s3eAdBuddizSetLogLevel(logLevel);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, (void*)g_Ext.m_s3eAdBuddizSetLogLevel);
#endif

    return ret;
}
