/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eAdBuddizRegister_t)(s3eAdBuddizCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eAdBuddizUnRegister_t)(s3eAdBuddizCallback cbid, s3eCallback fn);
typedef  s3eResult(*s3eAdBuddizInitialize_t)(const char* publisherKey);
typedef  s3eResult(*s3eAdBuddizSetTestMode_t)();
typedef  s3eResult(*s3eAdBuddizShowAd_t)();
typedef  s3eResult(*s3eAdBuddizSetLogLevel_t)(s3eAdBuddizLogLevel logLevel);

/**
 * struct that gets filled in by s3eAdBuddizRegister
 */
typedef struct s3eAdBuddizFuncs
{
    s3eAdBuddizRegister_t m_s3eAdBuddizRegister;
    s3eAdBuddizUnRegister_t m_s3eAdBuddizUnRegister;
    s3eAdBuddizInitialize_t m_s3eAdBuddizInitialize;
    s3eAdBuddizSetTestMode_t m_s3eAdBuddizSetTestMode;
    s3eAdBuddizShowAd_t m_s3eAdBuddizShowAd;
    s3eAdBuddizSetLogLevel_t m_s3eAdBuddizSetLogLevel;
} s3eAdBuddizFuncs;
