/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EADBUDDIZ_AUTODEFS_H
#define S3EADBUDDIZ_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADBUDDIZ_NAME "s3eAdBuddiz"
#define S3E_EXT_ADBUDDIZ_HASH 0x1b0b6597

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eAdBuddiz", 6)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EADBUDDIZ_AUTODEFS_H */
